# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    tags: [ 'v*' ] # Trigger on version tags

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build amd64
      run: GOOS=linux GOARCH=amd64 go build -v -o acm-secret-discovery-server-linux-amd64 -ldflags="-X main.Version=${{ github.ref_name }} -X main.Commit=${{ github.sha }}" .

    - name: Build arm64
      run: GOOS=linux GOARCH=arm64 go build -v -o acm-secret-discovery-server-linux-arm64 -ldflags="-X main.Version=${{ github.ref_name }} -X main.Commit=${{ github.sha }}" .

    - name: Build macOS arm64
      run: GOOS=darwin GOARCH=arm64 go build -v -o acm-secret-discovery-server-darwin-arm64 -ldflags="-X main.Version=${{ github.ref_name }} -X main.Commit=${{ github.sha }}" .

    - name: Test
      run: go test -v ./...

    - name: Create Release
      id: create_release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          LICENSE
          acm-secret-discovery-server-*

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push multi-arch image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/sixt/acm-secret-discovery-server:latest,ghcr.io/sixt/acm-secret-discovery-server:${{ github.ref_name }}
        build-args: |
          VERSION=${{ github.ref_name }}
          COMMIT=${{ github.sha }}